//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.34003
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.34003.
// 
#pragma warning disable 1591

namespace Didxazapp.webservice {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="DidxazAppserviceSoap", Namespace="http://didxaza-service.azurewebsites.net/service")]
    public partial class DidxazAppservice : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback HelloWorldOperationCompleted;
        
        private System.Threading.SendOrPostCallback quieropalabraenzapotecoOperationCompleted;
        
        private System.Threading.SendOrPostCallback quierofraseenzapotecoOperationCompleted;
        
        private System.Threading.SendOrPostCallback cuantoycuandoOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public DidxazAppservice() {
            this.Url = "http://didxaza-service.azurewebsites.net/service/didxaza.asmx";
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event HelloWorldCompletedEventHandler HelloWorldCompleted;
        
        /// <remarks/>
        public event quieropalabraenzapotecoCompletedEventHandler quieropalabraenzapotecoCompleted;
        
        /// <remarks/>
        public event quierofraseenzapotecoCompletedEventHandler quierofraseenzapotecoCompleted;
        
        /// <remarks/>
        public event cuantoycuandoCompletedEventHandler cuantoycuandoCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://didxaza-service.azurewebsites.net/service/HelloWorld", RequestNamespace="http://didxaza-service.azurewebsites.net/service", ResponseNamespace="http://didxaza-service.azurewebsites.net/service", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string HelloWorld() {
            object[] results = this.Invoke("HelloWorld", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void HelloWorldAsync() {
            this.HelloWorldAsync(null);
        }
        
        /// <remarks/>
        public void HelloWorldAsync(object userState) {
            if ((this.HelloWorldOperationCompleted == null)) {
                this.HelloWorldOperationCompleted = new System.Threading.SendOrPostCallback(this.OnHelloWorldOperationCompleted);
            }
            this.InvokeAsync("HelloWorld", new object[0], this.HelloWorldOperationCompleted, userState);
        }
        
        private void OnHelloWorldOperationCompleted(object arg) {
            if ((this.HelloWorldCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.HelloWorldCompleted(this, new HelloWorldCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://didxaza-service.azurewebsites.net/service/quieropalabraenzapoteco", RequestNamespace="http://didxaza-service.azurewebsites.net/service", ResponseNamespace="http://didxaza-service.azurewebsites.net/service", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string quieropalabraenzapoteco(string damelapalabraenezpañol) {
            object[] results = this.Invoke("quieropalabraenzapoteco", new object[] {
                        damelapalabraenezpañol});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void quieropalabraenzapotecoAsync(string damelapalabraenezpañol) {
            this.quieropalabraenzapotecoAsync(damelapalabraenezpañol, null);
        }
        
        /// <remarks/>
        public void quieropalabraenzapotecoAsync(string damelapalabraenezpañol, object userState) {
            if ((this.quieropalabraenzapotecoOperationCompleted == null)) {
                this.quieropalabraenzapotecoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnquieropalabraenzapotecoOperationCompleted);
            }
            this.InvokeAsync("quieropalabraenzapoteco", new object[] {
                        damelapalabraenezpañol}, this.quieropalabraenzapotecoOperationCompleted, userState);
        }
        
        private void OnquieropalabraenzapotecoOperationCompleted(object arg) {
            if ((this.quieropalabraenzapotecoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.quieropalabraenzapotecoCompleted(this, new quieropalabraenzapotecoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://didxaza-service.azurewebsites.net/service/quierofraseenzapoteco", RequestNamespace="http://didxaza-service.azurewebsites.net/service", ResponseNamespace="http://didxaza-service.azurewebsites.net/service", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string quierofraseenzapoteco(string damelafraseenespañol) {
            object[] results = this.Invoke("quierofraseenzapoteco", new object[] {
                        damelafraseenespañol});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void quierofraseenzapotecoAsync(string damelafraseenespañol) {
            this.quierofraseenzapotecoAsync(damelafraseenespañol, null);
        }
        
        /// <remarks/>
        public void quierofraseenzapotecoAsync(string damelafraseenespañol, object userState) {
            if ((this.quierofraseenzapotecoOperationCompleted == null)) {
                this.quierofraseenzapotecoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnquierofraseenzapotecoOperationCompleted);
            }
            this.InvokeAsync("quierofraseenzapoteco", new object[] {
                        damelafraseenespañol}, this.quierofraseenzapotecoOperationCompleted, userState);
        }
        
        private void OnquierofraseenzapotecoOperationCompleted(object arg) {
            if ((this.quierofraseenzapotecoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.quierofraseenzapotecoCompleted(this, new quierofraseenzapotecoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://didxaza-service.azurewebsites.net/service/cuantoycuando", RequestNamespace="http://didxaza-service.azurewebsites.net/service", ResponseNamespace="http://didxaza-service.azurewebsites.net/service", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string cuantoycuando() {
            object[] results = this.Invoke("cuantoycuando", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void cuantoycuandoAsync() {
            this.cuantoycuandoAsync(null);
        }
        
        /// <remarks/>
        public void cuantoycuandoAsync(object userState) {
            if ((this.cuantoycuandoOperationCompleted == null)) {
                this.cuantoycuandoOperationCompleted = new System.Threading.SendOrPostCallback(this.OncuantoycuandoOperationCompleted);
            }
            this.InvokeAsync("cuantoycuando", new object[0], this.cuantoycuandoOperationCompleted, userState);
        }
        
        private void OncuantoycuandoOperationCompleted(object arg) {
            if ((this.cuantoycuandoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.cuantoycuandoCompleted(this, new cuantoycuandoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void HelloWorldCompletedEventHandler(object sender, HelloWorldCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class HelloWorldCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal HelloWorldCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void quieropalabraenzapotecoCompletedEventHandler(object sender, quieropalabraenzapotecoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class quieropalabraenzapotecoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal quieropalabraenzapotecoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void quierofraseenzapotecoCompletedEventHandler(object sender, quierofraseenzapotecoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class quierofraseenzapotecoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal quierofraseenzapotecoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void cuantoycuandoCompletedEventHandler(object sender, cuantoycuandoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class cuantoycuandoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal cuantoycuandoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591